### ISSUE TITLE
Error when SSL certificate is renewed

### ISSUE THREAD

**Issue by bvanpoortvliet** [khoih-prog/EthernetWebServer_SSL#9] opened 2022-01-26 09:39 UTC
### Teensy 4.1 stops posting whenever the server it posts to renews its SSL certificate.

We are using a Teensy 4.1 in combination with your library in combination with QNEthernet to post data to an InfluxDB instance hosted on AWS. Recently we have discovered that the Teensy stops posting whenever the (3 month valid) SSL certificate on AWS renews, generating the errors below.

(EthernetSSLClient)(SSL_ERROR)(available): Cannot operate on a closed SSL connection.
(EthernetSSLClient)(SSL_ERROR)(m_print_br_error): Certificate is expired or not yet valid. 

Could you inform us what would be the best way to go about this issue without having to recompile and upload to the teensy? We plan to deploy around 500 Teensy's in the field spread over various countries, this is why recompiling and uploading every quarter is not an option for us. 

### Steps to Reproduce

Open WebClient_SSL or WebClientMulti_SSL from examples/EthernetWebServer_SSL/QNEthernet 
Generate trust anchors and paste in trust_anchors.h
Change request to POST and fill in correct host
Compile flash and run on Teensy
Check print-statements in serial monitor to check if post is successful
Change server certificate
Powercycle Teensy
Check print-statements in serial monitor to check if post is successful

### Expected behavior

Continuous posting when SSL certificate on server is renewed.

### Actual behavior

No post, these errors are generated:
(EthernetSSLClient)(SSL_ERROR)(available): Cannot operate on a closed SSL connection.
(EthernetSSLClient)(SSL_ERROR)(m_print_br_error): Certificate is expired or not yet valid. 

### Information
* Arduino IDE version 1.8.19
* Teensyduino 1.56
* Teensy 4.1
* OS: MacOS 12.1
* Darwin 21.2.0 Darwin Kernel Version 21.2.0: Sun Nov 28 20:29:10 PST 2021; root:xnu-8019.61.5~1/RELEASE_ARM64_T8101 arm64

**Comment by khoih-prog** [comment] 2022-01-26 15:37
Hi @bvanpoortvliet 

Thanks for your interest in the library and I'm glad that it's somehow useful to your use-case.

As you're experiencing, the usage of SSL (especially the drastic AWS way to update every 3 months its certificate) brings us the safety as well as the complexity the handle and manage.

SSL won't work unless we're updating the SSL certificates someway. 

---

IMHO, the best solution can be to rewrite the code to permit update the `trust anchors` **on-the-fly** by

1. Creating an HTTP/HTTPS server with updated `trust anchors`
2. Update the **server** `trust anchors` by writing a program / script to check with AWS
3. Teensy will periodically check and auto-update the `trust anchors` whenever there is mismatch (using checksum, etc.) between local and server  `trust anchors`. Anyway,  `trust anchors` is just a piece of manageable array of bytes.

---

Another not-so-bad solution is to connect the Teeensy **not directly** to AWS, but via a managed local server (running on PC, etc.), then the server will forward the requests / responses from/to Teensy

---

As this is an interesting scenario, I'd appreciate if you can post the solution / idea / discussion so that other users can benefit from it.

As this is not a bug or issue of the library, I'm closing this now and suggest that you open a [**discussion**](https://github.com/khoih-prog/EthernetWebServer_SSL/discussions) for this matter.

Regards,

**Closed by khoih-prog** 2022-01-26 15:37 UTC
